### ISSUE TITLE
Do not include Community Commons resources and userlib jars

### ISSUE THREAD

**Issue by reinouts** [mendix/IBM-Watson-Connector-Suite#20]
The suite contains outdated Community Commons resources and jars. These contain vulnerabilities which have been fixed in the latest Community Commons release. Please do not include these files in your connector suite. Thanks!

**Comment by zlogic** [comment]
Hi @reinouts, thank you for the advice!
These libraries and components will be removed in the next release.

**Comment by zlogic** [comment]
Fixed in [Watson Connector suite 7.0.0](https://appstore.home.mendix.com/link/app/2860/)
